# Generated by Django 4.2.4 on 2023-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Livro')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('idioma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma')),
                ('escritor', models.CharField(max_length=150, verbose_name='Escritor')),
                ('sinopse', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sinopse')),
                ('observacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observação')),
                ('compra', models.BooleanField(max_length=15, verbose_name='Preço de compra')),
                ('venda', models.BooleanField(max_length=15, verbose_name='Preço de venda')),
                ('data_compra', models.DateField(auto_now=True, verbose_name='Data da compra')),
                ('data_venda', models.DateField(auto_now=True, verbose_name='Data da venda')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/book/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
